url: https://estrelladebelenleon.com
baseurl: /

# Site settings
title: Iglesia Cristiana Bautista Estrella de Belén
email: your-email@domain.com
description: "¡Te damos la bienvenida a la Iglesia Cristiana Bautista Estrella de Belén en León, Guanajuato."


# Team names, titles and social links
people:
- name: Francisco Espinosa
  pic: 1
  position: Pastor
  social:
    - title: facebook
      url: #

- name: Erick Soria 
  pic: 2
  position: Ministro de Adoración 
  social:
    - title: facebook
      url: #

- name: Alicia Espinoza
  pic: 3
  position: Misionera
  social:
    - title: facebook
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://www.facebook.com/ibestrella
  - title: instagram
    url: https://www.instagram.com/ibeb.leon/

# Postal address (add as many lines as necessary)
address:
  - line: Paseo de las Codornices 111
  - line: San Isidro, 37685 León, Gto.

# Build settings
markdown: kramdown
permalink: pretty
